class Message():
    GetCard             = "get_card"
    GetListOfRoom       = "get_list_of_room"
    ListOfRooms         = "get_list_of_rooms"
    CreateRoom          = "create_room"
    RoomCreated         = "room_created"
    ConnectToRoom       = "connect_to_room"
    ConnectedToRoom     = "successfully_connected_to_room"
    PlayerConnected     = "player_connected"
    LeaveRoom           = "leave_room"
    DestroyRoom         = "destroy_room"
    RoomDestroyed       = "room_destroyed"
    PlayerDisconnected  = "player_disconnected"
    ChatMessage         = "chat_message"
    SetName             = "set_name"

    SUCCESS             = "SUCCESS"
    CriticalError       = "CriticalError"
    Error               = "Error"
